spring.application.name=socialposter-backend

server.port=${PORT:8080}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

linkedin.client.id=${LINKEDIN_CLIENT_ID}
linkedin.client.secret=${LINKEDIN_CLIENT_SECRET}
linkedin.redirect.uri=${LINKEDIN_REDIRECT_URI}

facebook.app.id=${FACEBOOK_APP_ID}
facebook.app.secret=${FACEBOOK_APP_SECRET}
facebook.redirect.uri=${FACEBOOK_REDIRECT_URI}